package org.ghostfish.as3introspection.factory
{
	import org.ghostfish.as3introspection.abc.RepresentationHierarchy;

	/**
	 * Defines the contract that any representation formatter must fulfill.
	 * 
	 * <p>The representation formatter is used by an instance of ABCWalker to
	 * process a representation hierarchy generated by an instance of 
	 * IRepresentationFactory.</p>
	 * 
	 * <p>Implementations of this interface get to choose just what processing
	 * the representation hierarchy involves. It might be the generation of,
	 * for example, an XML strucure that expresses the "public" contents of a
	 * SWF, or it might be, for example, some sort of file system or 
	 * socket-based generation process.</p>
	 */
	public interface IRepresentationFormatter
	{
		/**
		 * Processes a representation hierarchy.
		 * 
		 * @param hierarchy	The hierarchy to be processed.
		 */
		function process(hierarchy:RepresentationHierarchy):void;
	}
}